# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/pdx206-camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/pdx206-camera


PRODUCT_PACKAGES += \
    SomcCinemaPro-xxhdpi-release \
    ArtFilterCamera-xxhdpi-release \
    CameraPanorama-release \
    SemcCameraUI-xxhdpi-release \
    SomcPhotoPro-xxhdpi-release \
    com.sonymobile.addoncamera.portraitselfie
